<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MarketPlace.Order.Application\MarketPlace.Order.Application.csproj" />
    <ProjectReference Include="..\..\..\Shared\MarketPlace.Shared.Infrastructure\MarketPlace.Shared.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
